### ISSUE TITLE
SvelteKit add doesn't work

### ISSUE THREAD

**Issue by n-smits** [svelte-add/coffeescript#1]
```bash
npm init svelte@next
# Skeleton project, No to all options
npx svelte-add Leftium/coffeescript-adder
npm install
mv 'Leftium/coffeescript-adder/src/routes/examples/coffeescript.svelte' 'src/routes/'
npm run dev
# build fails
```

**Comment by Leftium** [comment]
The coffeescript adder needs to be updated  due to changes in SvelteKit. However, these updates are pending a rewrite of `svelte-add`. (See https://github.com/svelte-add/svelte-add/issues/23#issuecomment-822026490)

**Comment by babichjacob** [comment]
Closed by https://github.com/svelte-add/coffeescript/commit/cda003c369da511dd56ed60bc919a7bef9122a4a!
